### ISSUE TITLE
Allow RouteBuilder.using() to take a closure

### ISSUE THREAD

**Issue by mitchhentges** [marad/hyper-router#10]
Currently, `RouteBuilder.using()` only accepts a function pointer. 
```
Route::post("/messages").using(push_message)
```

I need the handler function to have access to some information at runtime, gathered before the `Hyper` server is started. Rather than having this data stored statically, I'd prefer to have my handler functions implemented on a struct, and I can make a closure to call them:

```
Route::post("/messages").using(|req, res| admin_handler.push_message(req, res))
```
`RouteBuilder` currently doesn't support this, because `Handler` is assumed to be a function pointer.

Can we make `Handler` be either a function pointer, _or_ a closure? (I looked into making a PR for this, with a `Handler` trait implemented by both `fn(Request, Response)` and `Fn(Request, Response)`, but I couldn't resolve the errors with `Sized`).

**Comment by mitchhentges** [comment]
A workaround that I have found is to define my handler functions within the scope of `fn main()`, after my important value is read:
```
fn main() {
    let value: String = calculate_value();

    fn push_message(_: Request, res: Response) {
        res.send(value.as_bytes()).unwrap();
    }

    let router = RouterBuilder::new()
        .add(Route::post("/messages").using(push_message))
        .build();
}
```

EDIT: workaround doesn't work: `error[E0434]: can't capture dynamic environment in a fn item; use the || { ... } closure form instead
`

**Comment by marad** [comment]
@mitchhentges I think that this would be really great if it worked as you suggest. Unfortunately I don't feel confident enough with Rust to make those changes. If you (or someone else) create PR for this, I'd be more than happy to accept it (after testing of course).

I'm leaving this issue open - maybe someone could solve it. Or maybe I'll try to figure it out myself later.

**Comment by marad** [comment]
@mitchhentges This seems to work fine now (with rust 1.22.1). Closing this issue.
