### ISSUE TITLE
Regex Example

### ISSUE THREAD

**Issue by dataf3l** [marad/hyper-router#13]
I'd like to use the hyper-router with regular expressions, how can I do this? is there an example somewhere?

**Comment by marad** [comment]
Hi @dataf3l!
Well, there is no example for that but when you're building the router you can just specify the path as regular expression:

```rust
let router = RouterBuilder::new()
    .add(Route::get("/gre?et").using(basic_handler))
    .build();
```

This would match `/gret` and `/greet` paths for this handler.

Please note that the regex you provide is prefixed with `^` and suffixed with `$`. This means that you have to specify the whole path to match. So the above example is not going to match `/something/greet` or `/greet/something`.
