### ISSUE TITLE
README example is missing hyper dependency

### ISSUE THREAD

**Issue by cardoe** [marad/hyper-router#8]
The example in the README is missing a dependency on `hyper`. 

```
$ cargo new --bin something
    Create binary (application) 'something' project
$ cd something
$ # add hyper-router to Cargo.toml
$ # copy and paste remaining README example as src/main.rs
$ cargo build
error[E0463]: can't find crate for `hyper`
 --> src/main.rs:1:1
  |
1 | extern crate hyper;
  | ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `something`.
```

Since `hyper-router` doesn't re-export all the pieces of `hyper` that are needed to use `hyper-router` then you need to `extern crate hyper` in `Cargo.toml`. As such `hyper-router` should ensure that semver bumps are done when changing the underlying dependency on `hyper`. And the README should be updated.

**Comment by marad** [comment]
Could you please create pull request with the fix? I'll be more than happy to accept it!

**Comment by marad** [comment]
Closing this, as it's old.
